default: true

MD001: false

MD003:
  style: "consistent"

MD004:
  style: "consistent"

MD005: true

MD007:
  indent:
  start_indented: false
  start_indent: 2

MD009:
  br_spaces: 2
  list_item_empty_lines: false
  strict: true

MD010:
  code_blocks: true
  ignore_code_languages: []
  spaces_per_tab: 4

MD011: true

MD012:
  maximum: 1

MD013: false

MD014: true

MD018: true

MD019: true

MD020: true

MD021: true

MD022:
  lines_above: 1
  lines_below: 1

MD023: true

MD024: false

MD025:
  level: 1
  front_matter_title: "^\\s*title\\s*[:=]"

MD026:
  punctuation: ".,;:!。，；：！"

MD027: true

MD028: true

MD029:
  style: "one_or_ordered"

MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

MD031:
  list_items: true

MD032: true

MD033: false

MD034: true

MD035:
  style: "consistent"

MD036:
  punctuation: ".,;:!?。，；：！？"

MD037: true

MD038: true

MD039: true

MD040:
  allowed_languages: []
  language_only: false

MD041:
  level: 1
  front_matter_title: "^\\s*title\\s*[:=]"

MD042: true

MD043: false

MD044:
  names: []
  code_blocks: true
  html_elements: true

MD045: false

MD046:
  style: "fenced"

MD047: true

MD048:
  style: "backtick"

MD049:
  style: "consistent"

MD050:
  style: "consistent"

MD051: true

MD052:
  shortcut_syntax: false


MD053:
  ignored_definitions:
    - "//"

MD054:
  autolink: false
  inline: true
  full: true
  collapsed: true
  shortcut: true
  url_inline: true

MD055:
  style: "consistent"

MD060: false
MD056: true
