extends:
  - spectral:oas
  - https://apistylebook.stoplight.io/docs/url-guidelines/ruleset.yaml
  - https://apistylebook.stoplight.io/docs/owasp-top-10/ruleset.yaml
rules:
  operation-summary-required:
    description: Every operation must have a summary.
    given: "$.paths[*][*]"
    severity: warn
    then:
      field: summary
      function: truthy

